base_url = "https://basemax.github.io/MindGarage"
title = "MindGarage"
description = "A clean and minimal blog about fixing the mind."
default_language = "en"
theme = "even"
compile_sass = false
minify_html = true
generate_rss = true
rss_limit = 20
taxonomies = [{ name = "tags" }]

[markdown]
highlight_code = true
