name: Deploy Zola site to GitHub Pages

on:
  push:
    branches:
      - main

env:
  ZOLA_VERSION: v0.20.0

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Cache Zola binary
        uses: actions/cache@v3
        id: zola-cache
        with:
          path: ~/.zola
          key: zola-${{ env.ZOLA_VERSION }}

      - name: Setup Zola
        run: |
          if [ ! -f ~/.zola/zola ]; then
            curl -L https://github.com/getzola/zola/releases/download/${ZOLA_VERSION}/zola-${ZOLA_VERSION}-x86_64-unknown-linux-gnu.tar.gz -o zola.tar.gz
            tar -xzf zola.tar.gz
            mkdir -p ~/.zola
            mv zola ~/.zola/
          fi
          sudo ln -sf ~/.zola/zola /usr/local/bin/zola
          zola --version

      - name: Build site
        run: zola build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
